# -*- coding: utf-8 -*-
"""GrayscaleBMP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TiFskoWh1kWoiwDSGhSCa8IdDC82Jp9r
"""

from PIL import Image



def png_to_bmp(name, number):


  img = Image.open(name)
  #Convert to gray image
  imgGray = img.convert('L')


  #Convert png to bmp 
  file_out = "./test{}.bmp".format(number)
  imgGray.save(file_out)